
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 06 19:38:08 CET 2024
//----------------------------------------------------

package mjc;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EQUALSTO = 27;
  public static final int CHAR = 48;
  public static final int CONST = 6;
  public static final int LESSE = 32;
  public static final int NAMESPACE = 17;
  public static final int LPAREN = 39;
  public static final int SEMI = 35;
  public static final int GREATER = 29;
  public static final int CONTINUE = 14;
  public static final int LESS = 31;
  public static final int FOR = 15;
  public static final int MINUS = 20;
  public static final int RPAREN = 40;
  public static final int STATIC = 16;
  public static final int AND = 25;
  public static final int OR = 26;
  public static final int BOOL = 45;
  public static final int COMMA = 38;
  public static final int CLASS = 4;
  public static final int INC = 33;
  public static final int DIV = 22;
  public static final int DIFFERENT = 28;
  public static final int PLUS = 19;
  public static final int IF = 7;
  public static final int LSQBRACE = 43;
  public static final int DOT = 37;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int EQUAL = 24;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int MUL = 21;
  public static final int NUMBER = 46;
  public static final int GREATERE = 30;
  public static final int MOD = 23;
  public static final int IDENT = 47;
  public static final int BREAK = 3;
  public static final int VOID = 12;
  public static final int ARROW = 18;
  public static final int COLON = 36;
  public static final int LBRACE = 41;
  public static final int ELSE = 5;
  public static final int READ = 10;
  public static final int RBRACE = 42;
  public static final int EXTENDS = 13;
  public static final int PROG = 2;
  public static final int RSQBRACE = 44;
  public static final int DEC = 34;
  public static final int PRINT = 9;
}

